# Generated by Django 3.0.5 on 2022-03-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patientInsuranceProvider',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientPolicyNumber',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='patientInsuranceProvider',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='patientPolicyNumber',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
