GET http://localhost:10000/diagnosis

###
GET http://localhost:10000/diagnosis/62411a91d459378394011d3e

###
POST http://localhost:10000/diagnosis
Content-Type: application/json

{
    "name": "Ravioli Jones",
    "labTests": "blood",
    "date": "2012-05-04"
}